### ISSUE TITLE
Create Load Balancer throws an error

### ISSUE THREAD

**Issue by philippeboyd** [digitalocean/droplet_kit#140]
I'm trying to create a load balancer but I'm getting this error.

I'm using the example from https://developers.digitalocean.com/documentation/v2/#create-a-new-load-balancer

It works fine using `curl` commands though...

```ruby
load_balancer = DropletKit::LoadBalancer.new(
  name: 'example-lb-01',
  algorithm: 'round_robin',
  droplet_ids: [],
  redirect_http_to_https: true,
  region: 'tor1',
  forwarding_rules: [
    DropletKit::ForwardingRule.new(
      entry_protocol: 'http',
      entry_port: 80,
      target_protocol: 'http',
      target_port: 80,
      certificate_id: '',
      tls_passthrough: false
    )
  ],
  sticky_sessions: DropletKit::StickySession.new(
    type: 'cookies',
    cookie_name: 'DO-LB',
    cookie_ttl_seconds: 5
  ),
  health_check: DropletKit::HealthCheck.new(
    protocol: 'http',
    port: 80,
    path: '/',
    check_interval_seconds: 10,
    response_timeout_seconds: 5,
    healthy_threshold: 5,
    unhealthy_threshold: 3
  )
)
client.load_balancers.create(load_balancer)
```

```bash
Traceback (most recent call last):
	6: from deploy.rb:281:in `<main>'
	5: from deploy.rb:275:in `main'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/resource_kit-0.1.7/lib/resource_kit/method_factory.rb:16:in `block in method_for_action'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:14:in `call'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:19:in `handle_response'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
/usr/local/lib/ruby/gems/2.5.0/gems/droplet_kit-2.2.2/lib/droplet_kit/error_handling_resourcable.rb:14:in `block (2 levels) in included': 500: {"id": "internal_server_error", "message": "Server was unable to give you a response." } (DropletKit::Error)
```

**Comment by viola** [comment]
@philippeboyd thanks for reporting this issue to us, just wanted to let you know I'm looking into it and will keep you posted when I have more information.

**Comment by philippeboyd** [comment]
hello @viola,
any news on this issue?

**Comment by viola** [comment]
Hi @philippeboyd sorry for a late response. Yes I have some updates.
I was able to reproduce and identify the issue, for the time being please use LB creates with empty tag field, such as: 

```
load_balancer = DropletKit::LoadBalancer.new(
  name: 'example-lb-01',
  algorithm: 'round_robin',
  droplet_ids: [],
  redirect_http_to_https: true,
  region: 'tor1',
  forwarding_rules: [
    DropletKit::ForwardingRule.new(
      entry_protocol: 'http',
      entry_port: 80,
      target_protocol: 'http',
      target_port: 80,
      certificate_id: '',
      tls_passthrough: false
    )
  ],
  sticky_sessions: DropletKit::StickySession.new(
    type: 'cookies',
    cookie_name: 'DO-LB',
    cookie_ttl_seconds: 5
  ),
  health_check: DropletKit::HealthCheck.new(
    protocol: 'http',
    port: 80,
    path: '/',
    check_interval_seconds: 10,
    response_timeout_seconds: 5,
    healthy_threshold: 5,
    unhealthy_threshold: 3
  ),
  tag: ""    # please set this
)
```
I will address that issue permanent on the server side (just didn't get around to do so yet, likely by the end of this Friday), and will update you when the fix is deployed to production. After that you will be able to skip specifying empty `tag` value. Please let me know if that tmp fix will work for you for the time being.

**Comment by philippeboyd** [comment]
Hello @viola,
**the workaround works great**! Event setting tags with a non empty array works. However, setting tags with an empty array will give the same exception. Here's a resume : 

```
// no tag field : not working
tag : [] same exception as above
tag : "" // Workaround
tag : ["tag1", "tag2"] // works
```

**Comment by viola** [comment]
@philippeboyd thanks bunch for your feedback! I will make sure to fully sanitize the `tag` field so there are no further issues with this field and workaround is no longer necessary.

**Comment by viola** [comment]
@philippeboyd I just wanted to let you know that the fix was deployed and the workaround for the tag attribute is no longer needed. Thank you for reporting this issue and for being patient while we allocate resources to address this bug.  
Note on the tag value: the expected values is a string, any other type is not permitted and will be strip off on the server side, for more info about `tag` value please check https://developers.digitalocean.com/documentation/v2/#create-a-new-load-balancer-with-droplet-tag

**Comment by philippeboyd** [comment]
@viola I have encountered another problem with the load balancer creation. Here are my observations :
`tls_passthrough` MUST be set (to `true` or `false`), default value doesn't work (as per the api doc)
`certificate_id` MUST NOT be `nil` and MUST exists, so for no certificate ID, it must be set to `''` (empty)

**Not working because certificate_id is `nil`**
```ruby
certificate_id = nil

load_balancer = DropletKit::LoadBalancer.new(
  name: "example-lb-01",
  algorithm: 'round_robin',
  droplet_ids: [],
  redirect_http_to_https: true,
  region: $global_options[:droplet_region],
  forwarding_rules: [
    DropletKit::ForwardingRule.new(
      entry_protocol: certificate_id ? 'https' : 'http',
      entry_port: certificate_id ? 443 : 80,
      target_protocol: 'http',
      target_port: 80,
      certificate_id: certificate_id,
      tls_passthrough: false
    )
  ],
  health_check: DropletKit::HealthCheck.new(
    protocol: 'http',
    port: 80,
    path: '/api/health',
    check_interval_seconds: 10,
    response_timeout_seconds: 5,
    healthy_threshold: 5,
    unhealthy_threshold: 3
  ),
  tag: "lb-blabala"
)

client.load_balancers.create(load_balancer)
```

**Not working because tls_passthrough is not set**
```ruby
load_balancer = DropletKit::LoadBalancer.new(
  name: "example-lb-01",
  algorithm: 'round_robin',
  droplet_ids: [],
  redirect_http_to_https: true,
  region: $global_options[:droplet_region],
  forwarding_rules: [
    DropletKit::ForwardingRule.new(
      entry_protocol: 'http',
      entry_port: 80,
      target_protocol: 'http',
      target_port: 80,
      certificate_id: ''
    )
  ],
  health_check: DropletKit::HealthCheck.new(
    protocol: 'http',
    port: 80,
    path: '/api/health',
    check_interval_seconds: 10,
    response_timeout_seconds: 5,
    healthy_threshold: 5,
    unhealthy_threshold: 3
  ),
  tag: "lb-blabala"
)

client.load_balancers.create(load_balancer)
```

**Not working because tls_passthrough AND certificate_id are not set**
```ruby
load_balancer = DropletKit::LoadBalancer.new(
  name: "example-lb-01",
  algorithm: 'round_robin',
  droplet_ids: [],
  redirect_http_to_https: true,
  region: $global_options[:droplet_region],
  forwarding_rules: [
    DropletKit::ForwardingRule.new(
      entry_protocol: 'http',
      entry_port: 80,
      target_protocol: 'http',
      target_port: 80
    )
  ],
  health_check: DropletKit::HealthCheck.new(
    protocol: 'http',
    port: 80,
    path: '/api/health',
    check_interval_seconds: 10,
    response_timeout_seconds: 5,
    healthy_threshold: 5,
    unhealthy_threshold: 3
  ),
  tag: "lb-blabala"
)

client.load_balancers.create(load_balancer)
```

**Works**
```ruby
load_balancer = DropletKit::LoadBalancer.new(
  name: "example-lb-01",
  algorithm: 'round_robin',
  droplet_ids: [],
  redirect_http_to_https: true,
  region: $global_options[:droplet_region],
  forwarding_rules: [
    DropletKit::ForwardingRule.new(
      entry_protocol: 'http',
      entry_port: 80,
      target_protocol: 'http',
      target_port: 80,
      certificate_id: '',
      tls_passthrough: false
    )
  ],
  health_check: DropletKit::HealthCheck.new(
    protocol: 'http',
    port: 80,
    path: '/api/health',
    check_interval_seconds: 10,
    response_timeout_seconds: 5,
    healthy_threshold: 5,
    unhealthy_threshold: 3
  ),
  tag: "lb-blabala"
)

client.load_balancers.create(load_balancer)
```

**Comment by viola** [comment]
@philippeboyd thanks for pointing that out. I also addressed these issues however that fix didn't go out with Friday release. However it went out today and it should be fixed by now. Please try again. 
Note: `tls_passthrough` nor `certificate_id`  should no longer be required to set to default values.

**Comment by philippeboyd** [comment]
Great thanks!

**Comment by jonnyarnold** [comment]
Hi there!

I've been using the Load Balancer API today and come across the same problem when using the example in the API documentation:

```ruby
load_balancer = @client.load_balancers.create(
  DropletKit::LoadBalancer.new(
    name: 'example-lb-01',
    algorithm: 'round_robin',
    droplet_ids: [],
    redirect_http_to_https: true,
    region: 'nyc3',
    forwarding_rules: [
      DropletKit::ForwardingRule.new(
        entry_protocol: 'http',
        entry_port: 80,
        target_protocol: 'http',
        target_port: 80,
        certificate_id: '',
        tls_passthrough: false
      ),
      DropletKit::ForwardingRule.new(
        entry_protocol: 'https',
        entry_port: 443,
        target_protocol: 'https',
        target_port: 443,
        certificate_id: '',
        tls_passthrough: true
      )
    ],
    sticky_sessions: DropletKit::StickySession.new(
      type: 'cookies',
      cookie_name: 'DO-LB',
      cookie_ttl_seconds: 5
    ),
    health_check: DropletKit::HealthCheck.new(
      protocol: 'http',
      port: 80,
      path: '/',
      check_interval_seconds: 10,
      response_timeout_seconds: 5,
      healthy_threshold: 5,
      unhealthy_threshold: 3
    )
  )
)
```

`@client` is a DropletKit::Client that successfully creates Droplets, DNS Records and Certificates in the same script file.

The error message I receive is:

```
/Library/Ruby/Gems/2.3.0/gems/droplet_kit-3.3.0/lib/droplet_kit/error_handling_resourcable.rb:14:in `block (2 levels) in included': 500: {"id": "internal_server_error", "message": "Server was unable to give you a response." } (DropletKit::Error)
	from /Library/Ruby/Gems/2.3.0/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
	from /Library/Ruby/Gems/2.3.0/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:19:in `handle_response'
	from /Library/Ruby/Gems/2.3.0/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:14:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/resource_kit-0.1.7/lib/resource_kit/method_factory.rb:16:in `block in method_for_action'
        ...
```

The Load Balancer is from the documentation; the one I want to make is as follows:

```rb
load_balancer = @client.load_balancers.create(
  DropletKit::LoadBalancer.new(
    name: self.name,
    algorithm: 'round_robin',
    droplet_ids: [self.droplet_id],
    redirect_http_to_https: true,
    region: 'lon1',
    forwarding_rules: [
      DropletKit::ForwardingRule.new(
        entry_protocol: 'https',
        entry_port: 443,
        target_protocol: 'http',
        target_port: 80,
        certificate_id: self.certificate.id,
        tls_passthrough: false
      )
    ],
    health_check: DropletKit::HealthCheck.new(
      protocol: 'http',
      port: 80,
      path: '/',
      check_interval_seconds: 10,
      response_timeout_seconds: 5,
      healthy_threshold: 3,
      unhealthy_threshold: 3
    )
  )
)
```

where `self.droplet_id` and `self.certificate.id` are existing droplets and certificates.

Let me know if I can help!

**Comment by andrewsomething** [comment]
Hi @jonnyarnold,

Thanks for flagging this issue! Can you try explicitly setting `enable_proxy_protocol: false`? It seems like Droplet Kit sends `"enable_proxy_protocol": null` in the request body if it is not set, and the API rejects that.

I've opened a new issue to track this separately: https://github.com/digitalocean/droplet_kit/issues/208

**Comment by jonnyarnold** [comment]
This does indeed fix the issue - thanks!
