### ISSUE TITLE
Unable to list SSH keys

### ISSUE THREAD

**Issue by adamonduty** [digitalocean/droplet_kit#37]
When I try to list the SSH keys:

```ruby
client.ssh_keys.all.each do |key|
  puts key.name
end
```

I'm presented with this error:

```
NoMethodError: undefined method `+' for :read:Symbol
	from /home/user/.rvm/gems/ruby-2.1.5/gems/kartograph-0.2.1/lib/kartograph/map.rb:14:in `property'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:9:in `block in <class:SSHKeyMapping>'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/kartograph-0.2.1/lib/kartograph/dsl.rb:12:in `instance_eval'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/kartograph-0.2.1/lib/kartograph/dsl.rb:12:in `kartograph'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:5:in `<class:SSHKeyMapping>'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:2:in `<module:DropletKit>'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:1:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/resources/ssh_key_resource.rb:7:in `block (3 levels) in <class:SSHKeyResource>'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/resource_kit-0.1.2/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/resource_kit-0.1.2/lib/resource_kit/action_invoker.rb:19:in `handle_response'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:68:in `retrieve'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:60:in `fetch_next_page'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:26:in `each'
```

I can create droplets without issue, so I'm assuming nothing is wrong with my setup.

**Comment by phillbaker** [comment]
@adamonduty what version of droplet kit are you using?

**Comment by adamonduty** [comment]
@phillbaker I'm using 1.1.3. Locking kartograph to 0.2.0 in my Gemfile fixes the issue, so it is the problem fixed in your pull request #36.

**Comment by adamonduty** [comment]
Maybe kartograph should splat the scopes <a href="https://github.com/digitalocean/kartograph/blob/master/lib/kartograph/property.rb#L39">here</a>, ie:

```ruby
[*options[:scopes]] || []
```

The splat will turn a single argument into an array, and leave an array untouched:

```
2.1.5 :005 > a = 1
 => 1
2.1.5 :006 > [*a]
 => [1]
2.1.5 :007 > a = [1,2]
 => [1, 2]
2.1.5 :008 > [*a]
 => [1, 2]
```

**Comment by adamonduty** [comment]
Err, wrong line, the bug starts <a href="https://github.com/digitalocean/kartograph/blob/master/lib/kartograph/map.rb#L13">here</a>, then breaks on the next line.

**Comment by phillbaker** [comment]
@adamonduty sounds like a good PR for kartograph! :grinning: Going to close this issue for now, #36 has been merged, we'll get a version bump out soon.
