### ISSUE TITLE
$digital_ocean.ssh_keys.all.first

### ISSUE THREAD

**Issue by ulugbekov** [digitalocean/droplet_kit#74]
```
NoMethodError: undefined method `+' for :read:Symbol
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/kartograph-0.2.4/lib/kartograph/map.rb:14:in `property'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/mappings/ssh_key_mapping.rb:9:in `block in <class:SSHKeyMapping>'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/kartograph-0.2.4/lib/kartograph/dsl.rb:12:in `instance_eval'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/kartograph-0.2.4/lib/kartograph/dsl.rb:12:in `kartograph'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/mappings/ssh_key_mapping.rb:5:in `<class:SSHKeyMapping>'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/mappings/ssh_key_mapping.rb:2:in `<module:DropletKit>'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/mappings/ssh_key_mapping.rb:1:in `<top (required)>'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/resources/ssh_key_resource.rb:7:in `block (3 levels) in <class:SSHKeyResource>'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.4/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.4/lib/resource_kit/action_invoker.rb:19:in `handle_response'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/paginated_resource.rb:62:in `retrieve'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/paginated_resource.rb:54:in `fetch_next_page'
	from /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.2/lib/droplet_kit/paginated_resource.rb:26:in `each'
	from (irb):8:in `first'
	from (irb):8
	from /Users/aulugbekov/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

**Comment by ulugbekov** [comment]
Upgraded version. Solved.
